name: build dist

on:
  create:
    tags:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: apt install
      run: |
        echo y | sudo apt-get install doxygen cmake ninja-build libasound2-dev
    - name: stupid NDK setup workaround for GitHub Actions
      run: sudo mkdir -p /usr/local/lib/android/sdk/ndk && sudo chmod 777 /usr/local/lib/android/sdk/ndk
    - name: setup gpg necessities
      run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > '$SIGNING_SECRET_KEY_RING_FILE'"
      env:
        GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    - name: rewrite build.gradle to require signing
      run: sed -i "s/signing {}/signing { sign(publishing.publications) }/" mugene/build.gradle.kts
    - name: publish to Maven and Npm
      run: |
        ./gradlew mugene:generateKotlinCommonGrammarSource
        ./gradlew build mugene-console-jvm:jar publish
      env:
        USERNAME: atsushieno
        GITHUB_TOKEN: ${{ secrets.MAVEN_PAT }}
        OSSRH_USERNAME: atsushieno
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: mugene-ng-artifacts
        path: |
          mugene/build/libs/*.jar
          mugene/build/outputs/aar/*.aar
          mugene-console/build/bin/
          mugene-console-jvm/build/libs/*.jar

