name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-22.04
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
    - name: apt install
      run: |
        echo y | sudo apt-get install doxygen cmake ninja-build libasound2-dev
    - name: build
      run: |
        ./gradlew build publishToMavenLocal mugene-console-jvm:jar
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: mugene-ng-artifacts
        path: |
          mugene/build/libs/*.jar
          mugene/build/outputs/aar/*.aar
          mugene-console/build/bin/
          mugene-console-jvm/build/libs/*.jar

